### ISSUE TITLE
Ownership of shipkit

### ISSUE THREAD

**Issue by TimvdLippe** [shipkit/shipkit-changelog#147]
@mockitoguy @shestee It seems that Shipkit has not received any substantial updates lately. Overall this plugin works as expected, but with Mockito we now hit an issue with it: https://github.com/mockito/mockito/issues/3235 To fix that, I filed #146 which appears to have an automated PR potentially solving it: #137

Would you be up to adding the Mockito core developers to maintain Shipkit as well, given that it originated from Mockito build plugins? That way, we can update the plugins and publish a new version so that we can unblock the Mockito release process.

**Comment by mockitoguy** [comment]
Working on it!
