### ISSUE TITLE
Document exact token permissions (read and write)

### ISSUE THREAD

**Issue by jplaisted** [shipkit/shipkit-changelog#20]
This probably applies to other plugins (main shipkit plugin too), since I can't find any docs.

Might be worth documenting the exact process for creating these tokens, including the exact permissions they need.

Also, I'm not sure the "read only" token is safe. As far as I can tell, the only token for GitHub is account wide (no repo specific tokens). And "read" includes reading your _private_ repos, which is probably not desired!

**Comment by mockitoguy** [comment]
"Read only token" (e.g. token with "no scope") provides access to *public* information (e.g. does not give read only access to private repositories).
