### ISSUE TITLE
Changelog shows bad commits author

### ISSUE THREAD

**Issue by mstachniuk** [shipkit/shipkit-changelog#21]
After merging of this PR: 
https://github.com/shipkit/shipkit-auto-version/pull/27
the generated changelog:
https://github.com/shipkit/shipkit-auto-version/releases/tag/v0.0.48
shows:
```
2020-10-07 - 1 commit(s) by Szczepan Faber
```
but should be:
```
2020-10-07 - 1 commit(s) by Marcin Stachniuk
```

**Comment by mockitoguy** [comment]
I figured out the problem. The CI build was not fetching all history hence the release notes only show a single commit. Fix: https://github.com/shipkit/shipkit-auto-version/pull/32
