### ISSUE TITLE
Customize tag format

### ISSUE THREAD

**Issue by mstachniuk** [shipkit/shipkit-changelog#24]
Currently tag format must contain a `v` prefix like `v1.2.3`. This should be configurable, e.g. to use just `1.2.3` tags.

**Comment by mockitoguy** [comment]
I'd wait for a customer requesting this before implementing. I know that Apache projects have "release-" prefix ([example](https://github.com/apache/incubator-gobblin/tree/release-0.15.0-rc1)). If we get popular (yay!) customizing the prefix will be a must.

**Comment by mockitoguy** [comment]
We should do it. We have a concrete use case: mockito-kotlin uses `1.2.3` notation and it's difficult to onboard shipkit plugins without disrupting the existing naming convention. See https://github.com/mockito/mockito-kotlin/releases
