### ISSUE TITLE
Predictable tagging

### ISSUE THREAD

**Issue by mockitoguy** [shipkit/shipkit-changelog#46]
When ```GitHubReleaseTask``` makes an API call to GitHub the server will create a new tag off origin/master. This introduces a race condition when a commit is introduced on origin/master just before ```GitHubReleaseTask``` makes the API call. Example problem reported by the customer: https://github.com/mockito/mockito/issues/2134.

We need to eliminate the race condition to ensure predictable tagging. When making API call we should specify the revision for the tag.

We should use ```target_commitish``` parameter when creating releases in [GitHubReleaseTask](https://github.com/shipkit/shipkit-changelog/blob/master/src/main/java/org/shipkit/gh/release/GitHubReleaseTask.java#L86). See [docs on releases API](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#create-a-release--parameters).

How do we get the revision? We can use ```GITHUB_SHA``` environment variable [provided by GH actions](https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables).

Example configuration of ```githubRelease``` task:

```Gradle
tasks.named("githubRelease") {
  //new task property allows specifying the revision used for the new tag
  //this property is nullable. When null, the tag we be created off origin/master
  newTagRevision = System.getenv("GITHUB_SHA");
  //...
}
```

**Comment by mockitoguy** [comment]
@shestee, do you want to take a stab at it? Thanks!

**Comment by shestee** [comment]
> @shestee, do you want to take a stab at it? Thanks!

Sure, I'll work on it. Thanks for asking!
