### ISSUE TITLE
Allow empty readOnlyToken

### ISSUE THREAD

**Issue by slawekjaranowski** [shipkit/shipkit-changelog#47]
On GitHub Action we can use auto generated token - `GITHUB_TOKEN` instead of hardcoded one in project for `readOnlyToken`

One limitation of such configuration is that we don't have token outside CI system, so running `generateChangelog` task on local environment is not possible.

In this situation for public repository we can allow run `generateChangelog` locally without token

**Comment by mockitoguy** [comment]
> In this situation for public repository we can allow run generateChangelog locally without token

Great idea. Do you want to take a stab at the implementation?

**Comment by slawekjaranowski** [comment]
😄 next week - first I want to finish work on mockito-testng
