### ISSUE TITLE
Simplify auth token configuration

### ISSUE THREAD

**Issue by mockitoguy** [shipkit/shipkit-changelog#50]
Currently, we recommend customers to use 2 different GH auth tokens:
 - read-only token is checked into the *.gradle file
 - write token is typically supplied via an env variable that is configured on the CI system

Problem statement:
 - checked-in token is used by web crawlers/robots or copy-pasted by engineers. This leads to token overuse that counts against the API rate limit
 - the user has to know/understand different types of tokens, complicating the setup and the configuration

Suggested solution:
 - update documentation and suggest customers to use a **single write token** that will be used for both: *auto-version* and *changelog* tasks.
 - to improve API consistency, rename task properties with deprecation: ```readOnlyToken``` -> ```githubToken```, ```writeToken``` -> ```githubToken```
 - update customers and make them use non-deprecated API

**Comment by mockitoguy** [comment]
@shestee, do you want to take a stab at this after #46?

**Comment by shestee** [comment]
Thanks, as you suggest I wil work on this after resolving #46.
