### ISSUE TITLE
Inconsistency in deployed and released versions ...

### ISSUE THREAD

**Issue by slawekjaranowski** [shipkit/shipkit-changelog#51]
At GitHub releases page https://github.com/shipkit/shipkit-changelog/releases we have the latest version: `v0.0.30`
but at:  https://plugins.gradle.org/plugin/org.shipkit.shipkit-changelog whe have the versions 
 - 1.0.0 (latest) Created 22 November 2020
 - 0.0.45 Created 04 October 2020
 - 0.0.30 Created 10 December 2020

and ... for `classpath "org.shipkit:shipkit-changelog:0.0.+"` gradle choose `0.0.45` it is something else which I suspect ...

**Comment by slawekjaranowski** [comment]
Similar
https://plugins.gradle.org/plugin/org.shipkit.shipkit-auto-version

**Comment by mockitoguy** [comment]
Thanks for reporting. I think I know what's going on but I need to check deeper.

**Comment by mockitoguy** [comment]
Update: I opened a ticket with Gradle to delete the 1.0 versions from the Plugin portal: https://github.com/gradle/plugin-portal-requests/issues/74

**Comment by mockitoguy** [comment]
I'm going to close this issue. We're releasing 1.1.* of both Shipkit plugins (auto-version and changelog). I asked Gradle to delete 1.0.0 from the plugin portal.
