### ISSUE TITLE
Remove unnecessary --scan from workflow files

### ISSUE THREAD

**Issue by mockitoguy** [shipkit/shipkit-changelog#56]
Let's remove unnecessary ```--scan``` from workflow files to keep the configuration simpler. Instead of ```--scan``` we can configure build scans in the *.gradle files using ```publishAlwaysIf()```: https://docs.gradle.com/enterprise/gradle-plugin/#publishing_based_on_criteria

Please apply this change to all Shipkit submodules and consumers we own.

**Comment by mockitoguy** [comment]
@shestee, do you want to take a look at it when you have a chance?

**Comment by shestee** [comment]
> @shestee, do you want to take a look at it when you have a chance?

Sure, thanks!
