### ISSUE TITLE
Update release notes if tag exists

### ISSUE THREAD

**Issue by mockitoguy** [shipkit/shipkit-changelog#97]
Update release notes if tag already exists to better support teams that release *on demand*.

- Current behavior: `githubRelease` task performs the release, fails when the tag already exists (error is returned from GH API REST call).
- New behavior: if the tag already exists, and the release notes are empty, update the release notes.

Implementation note: it should work for the case when someone pushed a tag via Git push (in this case the release does not exist but the tag exists) or when someone created GH release via UI (release exists, tag exists).

**Comment by mockitoguy** [comment]
@shestee, do you want to take a stab at this?

**Comment by shestee** [comment]
> @shestee, do you want to take a stab at this?

Yes, I will do it. Thank you for asking!

**Comment by mockitoguy** [comment]
Sample project: https://github.com/mockitoguy/shipkit-demo
